---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags: 
        - apt_get
      when: ansible_processor_nproc > 2 or ansible_os_family=="Debian"
    - name: install nginx on RedHat family
      package:
        name: httpd
        state: present
      when: ansible_processor_nproc > 2 or ansible_os_family=="RedHat"
    - name: start http deamon
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_processor_nproc > 2 or ansible_os_family=="RedHat"
    - name: create user Pierre
      user:
        name: Pierre
        comment: Pierre Cardin
        shell: /bin/bash
    - name: create group
      group:
        name: cloudteam
        state: present
    - name: create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags:
        - a
    - name: Read Data
      debug:
        var: file_output.diff.before.path
    - name: create  directory
      file: 
        path: /tmp/os
        state: directory

    - name: copy content to index
      copy:
        dest: file_output.diff.before.path
        content: '<h1>This is created using ansible</h1>'
